# Generated by Django 3.1.7 on 2021-03-19 23:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0002_auto_20210317_2306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderpositions',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='api_app.product'),
        ),
        migrations.AlterField(
            model_name='orderpositions',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
