# Generated by Django 3.1.7 on 2021-03-24 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20210324_2307'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderpositions',
            options={'verbose_name': 'Позиция', 'verbose_name_plural': 'Позиции'},
        ),
    ]
